// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"hardes/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/hardes/v1/conf/:id",
					Handler: saveHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/hardes/v1/conf/:id",
					Handler: getConfHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)
}
