// Code generated by goctl. DO NOT EDIT.
package types

type GetConfReq struct {
	ID    string `path:"id"`
	Token string `json:"token,required"`
}

type GetConfResp struct {
	ErrNo  int      `json:"errno"`
	ErrMsg string   `json:"errmsg"`
	Data   ConfData `json:"data"`
}

type ConfData struct {
}

type SaveReq struct {
	Token   string `json:"token,required"`
	Content string `json:"content"`
}

type SaveResp struct {
	ErrNo  int    `json:"errno"`
	ErrMsg string `json:"errmsg"`
}
